# ============================================================
# JingliuOS - rEFInd configuration
# ============================================================

timeout 20
use_nvram false

banner /EFI/refind/jingliu-banner.png
banner_scale noscale

hideui badges

scanfor manual


# ============================================================
# Operating Systems
# ============================================================

menuentry "NixOS" {
    icon /EFI/refind/icons/nixos-custom.png
    loader /EFI/systemd/systemd-bootx64.efi
}

menuentry "Windows" {
    icon /EFI/refind/icons/windows-custom.png
    volume 6462644C-9AF8-4B70-B485-9B13A870A8C8
    loader /EFI/Microsoft/Boot/bootmgfw.efi
}

resolution 2560 1600

showtools shutdown,reboot,firmware
