-- Jingliu — cold ice / deep blue / subtle crimson

JINGLIU_BLACK       = "rgba(080A10ff)"
JINGLIU_BACKGROUND  = "rgba(0A0E17ff)"
JINGLIU_SURFACE     = "rgba(121827ff)"
JINGLIU_SURFACE_ALT = "rgba(192337ff)"

JINGLIU_BORDER      = "rgba(465A78cc)"
JINGLIU_BLUE        = "rgba(547BBFff)"
JINGLIU_ICE         = "rgba(9CB9EAff)"
JINGLIU_LIGHT       = "rgba(C9D9F2ff)"
JINGLIU_CRIMSON     = "rgba(6F2336ff)"

JINGLIU_TEXT        = "rgba(E4EAF4ff)"
JINGLIU_MUTED       = "rgba(AAB7CAff)"
JINGLIU_DIM         = "rgba(7C899Eff)"

THEME_ACCENT_1 = JINGLIU_ICE
THEME_ACCENT_2 = JINGLIU_BLUE
THEME_ACCENT_3 = JINGLIU_LIGHT

THEME_BORDER = JINGLIU_BORDER
THEME_INACTIVE_BORDER = "rgba(465A7866)"

THEME_GLOW = "rgba(8EAEDB38)"
THEME_GLOW_INACTIVE = "rgba(547BBF18)"

THEME_BLUR_BRIGHTNESS = 0.78
THEME_BLUR_VIBRANCY = 0.12
THEME_BLUR_VIBRANCY_DARKNESS = 0.22

THEME_ACTIVE_OPACITY = 0.96
THEME_INACTIVE_OPACITY = 0.88
