{ pkgs, ... }:

pkgs.pywalfox-native.overrideAttrs (oldAttrs: {
  postInstall = (oldAttrs.postInstall or "") + ''
    mkdir -p $out/lib/mozilla/native-messaging-hosts

    cat > $out/lib/mozilla/native-messaging-hosts/pywalfox.json <<EOF2
{
  "name": "pywalfox",
  "description": "Automatically theme your browser using the colors generated by Pywal",
  "path": "$out/bin/pywalfox",
  "type": "stdio",
  "allowed_extensions": [ "pywalfox@frewacom.org" ]
}
EOF2
  '';
})
